apiVersion: v1
data:
  default.conf: |-
{{ .Values.nginxconfigmap.defaultConf | indent 4 }}
kind: ConfigMap
metadata:
  labels:
    app: '{{ template "fullname" . }}'
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-nginxconfigmap'
  namespace: '{{.Values.nginx.namespace}}'
