{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ template "fullname" . }}'
  labels:
    app: '{{ template "fullname" . }}'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific 
            backend:
              service:
                name: '{{ template "fullname" . }}'
                port:
                  number: {{ .Values.servicePort }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: '{{ template "fullname" . }}-tls'
      hosts:
        - {{ .Values.ingress.hostname }}
{{- end -}}
{{ end -}}
