
apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    app: '{{ template "fullname" . }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ template "fullname" . }}'
  namespace: '{{ .Values.nginx.namespace }}'
spec:
  ports:
  - name: https
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.nginx.containerPort }}
  selector:
    app: '{{ template "fullname" . }}'
  type: '{{ .Values.service.spec.serviceType }}'
